### ISSUE TITLE
panic: assignment to entry in nil map after startup

### ISSUE THREAD

**Issue by lub** [tulir/mautrix-whatsapp#119]
Hi,

I use dock.mau.dev/tulir/mautrix-whatsapp:latest with sqlite and the bridge sometimes crashes during startup:

```
[Dec  6, 2019 15:25:39] [Portal/redacted@s.whatsapp.net-redacted@s.whatsapp.net/INFO] Syncing portal for @redacted:imninja.net
panic: assignment to entry in nil map

goroutine 61 [running]:
maunium.net/go/mautrix.(*AnnotationChunk).UnmarshalJSON(0xc000406508, 0xc005046d56, 0x46, 0x4aa, 0x7f0c5e92c900, 0xc000406508)
       /builds/tulir/mautrix-whatsapp/.cache/pkg/mod/maunium.net/go/mautrix@v0.1.0-alpha.3.0.20191110191816-178ce1f1561d/relations.go:106 +0x168
encoding/json.(*decodeState).object(0xc0000ade40, 0xb8db00, 0xc000406508, 0x199, 0xc0000ade68, 0x7b)
       /usr/local/go/src/encoding/json/decode.go:667 +0x220b
encoding/json.(*decodeState).value(0xc0000ade40, 0xb8db00, 0xc000406508, 0x199, 0x1, 0xc0003c4650)
       /usr/local/go/src/encoding/json/decode.go:429 +0x6d
encoding/json.(*decodeState).object(0xc0000ade40, 0xb0c4c0, 0xc000406500, 0x16, 0xc0000ade68, 0xc004ffdd7b)
       /usr/local/go/src/encoding/json/decode.go:823 +0x1392
encoding/json.(*decodeState).value(0xc0000ade40, 0xb0c4c0, 0xc000406500, 0x16, 0xc00506a020, 0x513ef9)
       /usr/local/go/src/encoding/json/decode.go:429 +0x6d
encoding/json.(*decodeState).unmarshal(0xc0000ade40, 0xb0c4c0, 0xc000406500, 0xc0000ade68, 0x0)
       /usr/local/go/src/encoding/json/decode.go:179 +0x1fb
encoding/json.Unmarshal(0xc005046d45, 0x58, 0x4bb, 0xb0c4c0, 0xc000406500, 0x0, 0x0)
       /usr/local/go/src/encoding/json/decode.go:106 +0x112
maunium.net/go/mautrix.(*Relations).UnmarshalJSON(0xc000406500, 0xc005046d45, 0x58, 0x4bb, 0x7f0c5e92c8e0, 0xc000406500)
       /builds/tulir/mautrix-whatsapp/.cache/pkg/mod/maunium.net/go/mautrix@v0.1.0-alpha.3.0.20191110191816-178ce1f1561d/relations.go:166 +0xb6
encoding/json.(*decodeState).object(0xc00030bd08, 0xbb7c40, 0xc000406500, 0x199, 0xc00030bd30, 0x7b)
       /usr/local/go/src/encoding/json/decode.go:667 +0x220b
encoding/json.(*decodeState).value(0xc00030bd08, 0xbb7c40, 0xc000406500, 0x199, 0xbb7c40, 0xc000406500)
       /usr/local/go/src/encoding/json/decode.go:429 +0x6d
encoding/json.(*decodeState).object(0xc00030bd08, 0xbd87c0, 0xc0004064c0, 0x199, 0xc00030bd30, 0x7b)
       /usr/local/go/src/encoding/json/decode.go:823 +0x1392
encoding/json.(*decodeState).value(0xc00030bd08, 0xbd87c0, 0xc0004064c0, 0x199, 0xbd87c0, 0xc0004064c0)
       /usr/local/go/src/encoding/json/decode.go:429 +0x6d
encoding/json.(*decodeState).object(0xc00030bd08, 0xb06540, 0xc000421e60, 0x16, 0xc00030bd30, 0x7b)
       /usr/local/go/src/encoding/json/decode.go:823 +0x1392
encoding/json.(*decodeState).value(0xc00030bd08, 0xb06540, 0xc000421e60, 0x16, 0xc005014a50, 0x515dfe)
       /usr/local/go/src/encoding/json/decode.go:429 +0x6d
encoding/json.(*decodeState).unmarshal(0xc00030bd08, 0xb06540, 0xc000421e60, 0x0, 0xc005014901)
       /usr/local/go/src/encoding/json/decode.go:179 +0x1fb
encoding/json.(*Decoder).Decode(0xc00030bce0, 0xb06540, 0xc000421e60, 0xcfffa0, 0xc00043b000)
       /usr/local/go/src/encoding/json/stream.go:73 +0x166
maunium.net/go/mautrix.(*Client).MakeRequest(0xc000172240, 0xc1b731, 0x3, 0xc0001f8900, 0xab, 0x0, 0x0, 0xafb440, 0xc00018aa08, 0x0, ...)
       /builds/tulir/mautrix-whatsapp/.cache/pkg/mod/maunium.net/go/mautrix@v0.1.0-alpha.3.0.20191110191816-178ce1f1561d/client.go:330 +0x5a8
maunium.net/go/mautrix.(*Client).GetEvent(0xc000172240, 0xc004f7bc00, 0x1f, 0xc004ee5770, 0x2c, 0x3, 0xc00503cb80, 0x0)
       /builds/tulir/mautrix-whatsapp/.cache/pkg/mod/maunium.net/go/mautrix@v0.1.0-alpha.3.0.20191110191816-178ce1f1561d/client.go:867 +0x207
main.(*Portal).SetReply(0xc004fa7c00, 0xc004d2b4a0, 0xc00504c000, 0x20, 0xc004d27d00, 0xc00504c020, 0x1c, 0x0)
       /builds/tulir/mautrix-whatsapp/portal.go:851 +0x1fe
main.(*Portal).HandleTextMessage(0xc004fa7c00, 0xc0002be0e0, 0xc004fbdfc0, 0x20, 0xc004fbdfa0, 0x1d, 0x0, 0x0, 0x0, 0x5de76793, ...)
       /builds/tulir/mautrix-whatsapp/portal.go:927 +0x184
main.(*Portal).handleMessage(0xc004fa7c00, 0xc004f7bbc0, 0x1d, 0xc0002be0e0, 0xba0740, 0xc004d32780, 0x5de76793)
       /builds/tulir/mautrix-whatsapp/portal.go:193 +0xd75
main.(*Portal).handleHistory(0xc004fa7c00, 0xc0002be0e0, 0xc00041d620, 0x2, 0x2)
       /builds/tulir/mautrix-whatsapp/portal.go:707 +0x272
main.(*Portal).BackfillHistory(0xc004fa7c00, 0xc0002be0e0, 0x5de76836, 0x0, 0x0)
       /builds/tulir/mautrix-whatsapp/portal.go:603 +0x3bf
main.(*User).syncPortals(0xc0002be0e0, 0xc0002aeea0, 0xc00029e900)
       /builds/tulir/mautrix-whatsapp/user.go:449 +0xc62
created by main.(*User).HandleChatList
       /builds/tulir/mautrix-whatsapp/user.go:400 +0x33b
```

**Comment by tulir** [comment]
This seems to be fixed now
