### ISSUE TITLE
Crashing due to error in sync when  calling GetProfilePicThumb

### ISSUE THREAD

**Issue by devilankur18** [tulir/mautrix-whatsapp#146]
I am attaching the stack trace as below

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x927d7e]



goroutine 39664 [running]:
github.com/Rhymen/go-whatsapp.(*Conn).write(0xc00045a700, 0x1, 0xc023df7560, 0xf, 0xc000fd5130, 0x49, 0x50, 0x0, 0x12919a0, 0x7f57f39d9460)
        /go/pkg/mod/github.com/tulir/go-whatsapp@v0.0.2-0.20191109203156-c477dae1c7e9/write.go:130 +0x3e
github.com/Rhymen/go-whatsapp.(*Conn).writeJson(0xc00045a700, 0xc00bd13140, 0x3, 0x3, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/tulir/go-whatsapp@v0.0.2-0.20191109203156-c477dae1c7e9/write.go:33 +0x32d
github.com/Rhymen/go-whatsapp.(*Conn).GetProfilePicThumb(...)
        /go/pkg/mod/github.com/tulir/go-whatsapp@v0.0.2-0.20191109203156-c477dae1c7e9/contact.go:25
maunium.net/go/mautrix-whatsapp/whatsapp-ext.(*ExtendedConn).GetProfilePicThumb(0xc0010d9020, 0xc027d8f760, 0x1b, 0x1, 0xc0000de800, 0x80)
        /build/whatsapp-ext/whatsapp.go:151 +0x101
main.(*Puppet).UpdateAvatar(0xc013f303f0, 0xc0004afae0, 0x0, 0x1b)
        /build/puppet.go:183 +0x7d2
main.(*Puppet).Sync(0xc013f303f0, 0xc0004afae0, 0xc037e43780, 0x1b, 0xc037962a80, 0x22, 0x0, 0x0, 0x0, 0x0)
        /build/puppet.go:296 +0x1a9
main.(*User).syncPuppets(0xc0004afae0)
        /build/user.go:553 +0x23a
created by main.(*User).intPostLogin
        /build/user.go:474 +0x2a0
```

**Comment by tulir** [comment]
I think go-whatsapp handles calls after disconnecting by returning an error instead of panicking now
