### ISSUE TITLE
Connection issues lead to segmentation violation

### ISSUE THREAD

**Issue by Rafaeltheraven** [tulir/mautrix-whatsapp#172]
The past few days mautrix-whatsapp has been crashing on me almost daily. Looking at the logs, I am presented with the following (anonymized) errors:

```
[User/@user1:homeserver/ERROR] WhatsApp error: keepAlive failed: connection timed out
[User/@user1:homeserver/ERROR] WhatsApp JSON parse error: json: cannot unmarshal number into Go value of 
[User/@user1:homeserver/ERROR] WhatsApp error: keepAlive failed: connection timed out
[User/@user2:homeserver/ERROR] WhatsApp error: connection to WhatsApp servers failed: websocket: close 1006 
[User/@user2:homeserver/ERROR] Error while trying to reconnect after disconnection: restore session 
[User/@user2:homeserver/ERROR] Error while trying to reconnect after disconnection: init responded with 400
[User/@user1:homeserver/ERROR] WhatsApp error: connection to WhatsApp servers failed: websocket: close 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7a234f]
goroutine 171977 [running]:
github.com/Rhymen/go-whatsapp.(*Conn).Disconnect(0xc00014c000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/user2/go/pkg/mod/github.com/tulir/go-whatsapp@v0.2.6/conn.go:218 +0x7f
github.com/Rhymen/go-whatsapp.(*Conn).readPump.func1(0xc00014c000)
        /home/user2/go/pkg/mod/github.com/tulir/go-whatsapp@v0.2.6/read.go:21 +0x5a
github.com/Rhymen/go-whatsapp.(*Conn).readPump(0xc00014c000)
        /home/user2/go/pkg/mod/github.com/tulir/go-whatsapp@v0.2.6/read.go:40 +0x368
created by github.com/Rhymen/go-whatsapp.(*Conn).connect
        /home/user2/go/pkg/mod/github.com/tulir/go-whatsapp@v0.2.6/conn.go:201 +0x3ab
```

This is on the latest version of the bridge, pulled directly from the `master` branch.

**Comment by tulir** [comment]
This might be fixed on the latest version, although I'm not exactly sure what caused that state and if it should do something else than a simple nil check
