### ISSUE TITLE
E2E Encryption /syncing timeout

### ISSUE THREAD

**Issue by Brunfunstudios** [tulir/mautrix-whatsapp#196]
Hello everyone,
First of all Thank you very much for this awesome project!

I've encountered an issues when trying to use E2E.
After setting up the login_shared_secret and allowing enryption the bridge reports:
```[Jun 11, 2020 12:49:59] [Crypto/ERROR] Error /syncing, waiting 10 seconds: msg=Failed to GET JSON to /_matrix/client/r0/sync code=500 wrapped=M_UNKNOWN: Internal server error```

On the Server side:
```
Jun 11 12:48:48 freedombox synapse[15564]: synapse.http.server: [GET-577] Failed handle request via 'SyncRestServlet': <SynapseRequest at 0xb1eaaf50 method='GET' uri='/_matrix/client/r0/sync?filter=

Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/synapse/http/server.py", line 78, in wrapped_request_handler await h(self, request)
File "/usr/lib/python3/dist-packages/synapse/http/server.py", line 331, in _async_render callback_return = await callback_return
File "/usr/lib/python3/dist-packages/synapse/rest/client/v2_alpha/sync.py", line 178, in on_GET
full_state=full_state,
File "/usr/lib/python3/dist-packages/synapse/handlers/sync.py", line 286, in wait_for_sync_for_user
full_state,
File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
result = g.send(result)
File "/usr/lib/python3/dist-packages/synapse/handlers/sync.py", line 312, in _wait_for_sync_for_user
sync_config, since_token, full_state=full_state
File "/usr/lib/python3/dist-packages/synapse/handlers/sync.py", line 343, in current_sync_for_user
return await self.generate_sync_result(sync_config, since_token, full_state)
File "/usr/lib/python3/dist-packages/synapse/handlers/sync.py", line 982, in generate_sync_result
raise NotImplementedError()
NotImplementedError
```

After looking through the Synapse github issues i found [this issue](https://github.com/matrix-org/synapse/issues/3376) which looks similar. 

Thank you for your time.

**Comment by tulir** [comment]
As the [config](https://github.com/tulir/mautrix-whatsapp/blob/master/example-config.yaml#L159-L160) says, it won't work by default. https://github.com/tulir/mautrix-telegram/wiki/End‐to‐bridge-encryption has a workaround that doesn't involve patching synapse.
