### ISSUE TITLE
Crashes when sending message if relaybot is enabled

### ISSUE THREAD

**Issue by mrjohnson22** [tulir/mautrix-whatsapp#207]
Steps to reproduce:

1. enable relaybot mode in the config file by applying these `relaybot` settings:
   - `enabled: true`
   - `management: "<id_of_existing_room>"`
   - `invites: ["<your_mxid>"]`
2. start a direct what with the WA bot, and also invite it to the `relaybot.management` room
3. join a WA portal room in bridge mode by posting `open <jid>` in the direct chat with the bot and accepting the invite it sends
4. enable relaybot mode with `!wa login` in the relaybot management room
5. post a message in the WA portal room

Expected results: your message will be bridged to WhatsApp
Actual results: the bridge segfaults with:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x85fe95]

goroutine 413 [running]:
github.com/Rhymen/go-whatsapp.(*Conn).write(0xc0003c6000, 0x2, 0xc000623860, 0x14, 0xc0000562c0, 0xa7, 0xb0, 0xb0, 0x90, 0x0)
	/home/<user>/go/pkg/mod/github.com/tulir/go-whatsapp@v0.3.4/write.go:131 +0x45
github.com/Rhymen/go-whatsapp.(*Conn).writeBinary(0xc0003c6000, 0xda6b63, 0x6, 0xc0002445a0, 0xc6c260, 0xc0004e27a0, 0xc000028010, 0xc000623860, 0x14, 0x0, ...)
	/home/<user>/go/pkg/mod/github.com/tulir/go-whatsapp@v0.3.4/write.go:59 +0x23d
github.com/Rhymen/go-whatsapp.(*Conn).sendProto(0xc0003c6000, 0xc0003ea5a0, 0x48ecec, 0xde5ad8, 0xc000329778)
	/home/<user>/go/pkg/mod/github.com/tulir/go-whatsapp@v0.3.4/message.go:127 +0x22e
github.com/Rhymen/go-whatsapp.(*Conn).SendRaw(0xc0003c6000, 0xc0003ea5a0, 0xc000280360)
	/home/<user>/go/pkg/mod/github.com/tulir/go-whatsapp@v0.3.4/message.go:29 +0x55
created by main.(*Portal).HandleMatrixMessage
	/home/<user>/git/mautrix-whatsapp/portal.go:1953 +0x29b
```

This happens even when using the direct chat with the bot as the relaybot management room.

It also doesn't make a difference if the `open <jid>` command is handled by the relaybot mode instead of by the default/bridge mode.

Not sure if this happens when joining a WA portal room that was created automatically by the bot, instead of one that was created manually with `open <jid>`.

If it matters, the bridge also posts this error message when relaybot mode is enabled and the bridge bot is present in a portal room:
```
[Portal/<jid>/ERROR] Failed to change power levels: msg=Failed to PUT JSON to /_matrix/client/r0/rooms/<room_id>/state/m.room.power_levels/ code=400 wrapped=M_UNKNOWN: Not a valid user_id: relaybot
```

It seems that the bridge uses an internal mxid of `relaybot`, but it's not a fully-qualified mxid (it's not `@relaybot:domain`) and no appservice user was ever created for it, so synapse returns a 400 error.

My usecase is that I want to enable relaying for an existing WA room. I'm testing this on a dummy homeserver before trying it my production homeserver, so I'm using `open <jid>` on the dummy server to first create a WA portal room, in order to simulate having already been in a portal room and enabling relaymode afterwards.

**Comment by mrjohnson22** [comment]
The same crash happens when any Matrix user posts in a relaybot-enabled room, not just the Matrix user who's logged into the WA bridge.
