### ISSUE TITLE
migrate-db, sqlite to postgres failure

### ISSUE THREAD

**Issue by rajil** [tulir/mautrix-whatsapp#211]
I have a sqlite3 database and trying to migrate to postgres.

```
# sudo -u mautrix-whatsapp /usr/local/bin/mautrix-whatsapp -c /etc/mautrix-whatsapp/config.yaml  --migrate-db sqlite3 /var/lib/mautrix-whatsapp/mautrix-whatsapp.db
sudo: setrlimit(RLIMIT_CORE): Operation not permitted
[20:23:29 21.07.2020] [Database/Upgrade/INFO] Database currently on v18, latest: v18
[20:23:29 21.07.2020] [Database/Upgrade/INFO] Database currently on v0, latest: v18
[20:23:29 21.07.2020] [Database/Upgrade/INFO] Upgrading database to v1: Initial schema
[20:23:29 21.07.2020] [Database/Upgrade/INFO] Upgrading database to v2: Add ON DELETE CASCADE to message table
[20:23:29 21.07.2020] [Database/Upgrade/INFO] Upgrading database to v3: Add timestamp column to messages
[20:23:29 21.07.2020] [Database/Upgrade/INFO] Upgrading database to v4: Add last_connection column to users
[20:23:29 21.07.2020] [Database/Upgrade/INFO] Upgrading database to v5: Update message content to new protocol version. This may take a while.
[20:23:29 21.07.2020] [Database/Upgrade/INFO] Upgrading database to v6: Add columns to store custom puppet info
[20:23:29 21.07.2020] [Database/Upgrade/INFO] Upgrading database to v7: Add user-portal mapping table
[20:23:29 21.07.2020] [Database/Upgrade/INFO] Upgrading database to v8: Add columns to store avatar MXC URIs
[20:23:29 21.07.2020] [Database/Upgrade/INFO] Upgrading database to v9: Add columns to store portal in filtering community meta
[20:23:29 21.07.2020] [Database/Upgrade/INFO] Upgrading database to v10: Move state store to main DB
[20:23:29 21.07.2020] [Database/Upgrade/INFO] Upgrading database to v11: Add columns to store full member info in state store
[20:23:29 21.07.2020] [Database/Upgrade/INFO] Upgrading database to v12: Adjust the length of column topic in portal
[20:23:29 21.07.2020] [Database/Upgrade/INFO] Upgrading database to v13: Add encryption status to portal table
[20:23:29 21.07.2020] [Database/Upgrade/INFO] Upgrading database to v14: Add crypto store to database
[20:23:29 21.07.2020] [Database/Upgrade/INFO] Upgrading database to v15: Add outbound group sessions to database
[20:23:29 21.07.2020] [Database/Upgrade/INFO] Upgrading database to v16: Add enable_presence column for puppets
[20:23:29 21.07.2020] [Database/Upgrade/INFO] Upgrading database to v17: Add account_id to crypto store
[20:23:29 21.07.2020] [Database/Upgrade/INFO] Upgrading database to v18: Add enable_receipts column for puppets
Migrating portal: found 102 rows of data, migrating in 2 batches: ## -- done with 101 rows inserted
Migrating user: found 1 rows of data, migrating in 1 batches: # -- done with 1 rows inserted
Migrating puppet: found 1033 rows of data, migrating in 17 batches: ################panic: pq: syntax error at end of input

goroutine 1 [running]:
maunium.net/go/mautrix-whatsapp/database.migrateTable(0xc00007c280, 0xc00007c4b0, 0xd9e3eb, 0x6, 0xc0001b7c18, 0x8, 0x8, 0x0, 0x0)
        /home/ubuntu/tmp/mautrix-whatsapp/database/migrate.go:76 +0xde8
maunium.net/go/mautrix-whatsapp/database.Migrate(0xc00007c280, 0xc00007c4b0)
        /home/ubuntu/tmp/mautrix-whatsapp/database/migrate.go:100 +0x465
main.(*Bridge).MigrateDatabase(0xc0000344e0)
        /home/ubuntu/tmp/mautrix-whatsapp/main.go:124 +0x364
main.(*Bridge).Main(0xc0000344e0)
        /home/ubuntu/tmp/mautrix-whatsapp/main.go:400 +0x4b
main.main()
        /home/ubuntu/tmp/mautrix-whatsapp/main.go:445 +0x116
```

**Comment by rajil** [comment]
I tried the latest version to migrate the database.

```
# sudo -u mautrix-whatsapp /usr/local/bin/mautrix-whatsapp -v
sudo: setrlimit(RLIMIT_CORE): Operation not permitted
mautrix-whatsapp 0.1.3+dev.1b1d5d9a (Aug  1 2020, 20:11:25)
```
It failed with the following message.
```
# sudo -u mautrix-whatsapp /usr/local/bin/mautrix-whatsapp -c /etc/mautrix-whatsapp/config.yaml  --migrate-db sqlite3 /var/lib/mautrix-whatsapp/mautrix-whatsapp.db
sudo: setrlimit(RLIMIT_CORE): Operation not permitted
[20:16:33 01.08.2020] [Database/Upgrade/INFO] Database currently on v18, latest: v18
[20:16:33 01.08.2020] [Database/Upgrade/INFO] Database currently on v0, latest: v18
[20:16:33 01.08.2020] [Database/Upgrade/INFO] Upgrading database to v1: Initial schema
[20:16:33 01.08.2020] [Database/Upgrade/INFO] Upgrading database to v2: Add ON DELETE CASCADE to message table
[20:16:33 01.08.2020] [Database/Upgrade/INFO] Upgrading database to v3: Add timestamp column to messages
[20:16:33 01.08.2020] [Database/Upgrade/INFO] Upgrading database to v4: Add last_connection column to users
[20:16:33 01.08.2020] [Database/Upgrade/INFO] Upgrading database to v5: Update message content to new protocol version. This may take a while.
[20:16:33 01.08.2020] [Database/Upgrade/INFO] Upgrading database to v6: Add columns to store custom puppet info
[20:16:33 01.08.2020] [Database/Upgrade/INFO] Upgrading database to v7: Add user-portal mapping table
[20:16:33 01.08.2020] [Database/Upgrade/INFO] Upgrading database to v8: Add columns to store avatar MXC URIs
[20:16:33 01.08.2020] [Database/Upgrade/INFO] Upgrading database to v9: Add columns to store portal in filtering community meta
[20:16:33 01.08.2020] [Database/Upgrade/INFO] Upgrading database to v10: Move state store to main DB
[20:16:33 01.08.2020] [Database/Upgrade/INFO] Upgrading database to v11: Add columns to store full member info in state store
[20:16:33 01.08.2020] [Database/Upgrade/INFO] Upgrading database to v12: Adjust the length of column topic in portal
[20:16:33 01.08.2020] [Database/Upgrade/INFO] Upgrading database to v13: Add encryption status to portal table
[20:16:33 01.08.2020] [Database/Upgrade/INFO] Upgrading database to v14: Add crypto store to database
[20:16:33 01.08.2020] [Database/Upgrade/INFO] Upgrading database to v15: Add outbound group sessions to database
[20:16:33 01.08.2020] [Database/Upgrade/INFO] Upgrading database to v16: Add enable_presence column for puppets
[20:16:33 01.08.2020] [Database/Upgrade/INFO] Upgrading database to v17: Add account_id to crypto store
[20:16:33 01.08.2020] [Database/Upgrade/INFO] Upgrading database to v18: Add enable_receipts column for puppets
Migrating portal: found 104 rows of data, migrating in 2 batches: ## -- done with 103 rows inserted
Migrating user: found 1 rows of data, migrating in 1 batches: # -- done with 1 rows inserted
Migrating puppet: found 1514 rows of data, migrating in 30 batches: ############################## -- done with 1485 rows inserted
Migrating user_portal: found 100 rows of data, migrating in 1 batches: panic: pq: insert or update on table "user_portal" violates foreign key constraint "user_portal_portal_jid_portal_receiver_fkey"

goroutine 1 [running]:
maunium.net/go/mautrix-whatsapp/database.migrateTable(0xc0002821e0, 0xc000282410, 0xdbba5f, 0xb, 0xc000541a10, 0x4, 0x4, 0x0, 0x0)
        /home/ubuntu/tmp/mautrix-whatsapp/database/migrate.go:79 +0xdf6
maunium.net/go/mautrix-whatsapp/database.Migrate(0xc0002821e0, 0xc000282410)
        /home/ubuntu/tmp/mautrix-whatsapp/database/migrate.go:107 +0x59e
main.(*Bridge).MigrateDatabase(0xc000034270)
        /home/ubuntu/tmp/mautrix-whatsapp/main.go:121 +0x350
main.(*Bridge).Main(0xc000034270)
        /home/ubuntu/tmp/mautrix-whatsapp/main.go:397 +0x4b
main.main()
        /home/ubuntu/tmp/mautrix-whatsapp/main.go:439 +0x116
```

**Comment by tulir** [comment]
That's a different issue (#214)
