### ISSUE TITLE
SIGSEGV after reconnect

### ISSUE THREAD

**Issue by jahlives** [tulir/mautrix-whatsapp#309]
quite out-of-the-blue I'm getting SIGSEGV errors from mautrix-whatsapp when sending `reconnect` command to bot
```
mautrix-whatsapp        | 2021-05-26T15:49:40.825231775Z [May 26, 2021 15:49:40] [Command handler/DEBUG] @redacted:redacted sent 'reconnect' in !GGrJDTYczxWvzoEiJO:redacted
mautrix-whatsapp        | 2021-05-26T15:49:40.825336332Z [May 26, 2021 15:49:40] [User/@redacted:redacted/Conn/DEBUG] Disconnecting websocket
mautrix-whatsapp        | 2021-05-26T15:49:40.825348902Z [May 26, 2021 15:49:40] [User/@redacted:redacted/Conn/DEBUG] Websocket keepalive loop exiting 0xc00024e0a0
mautrix-whatsapp        | 2021-05-26T15:49:40.825357554Z [May 26, 2021 15:49:40] [User/@redacted:redacted/Conn/DEBUG] Websocket read pump exiting 0xc00024e0a0
mautrix-whatsapp        | 2021-05-26T15:49:40.825405081Z [May 26, 2021 15:49:40] [User/@redacted:redacted/ERROR] Failed to restore session: connection closed before login finished
mautrix-whatsapp        | 2021-05-26T15:49:40.826899266Z [May 26, 2021 15:49:40] [User/@redacted:redacted/Conn/DEBUG] Websocket disconnection complete
mautrix-whatsapp        | 2021-05-26T15:49:40.826922595Z [May 26, 2021 15:49:40] [User/@redacted:redacted/Conn/DEBUG] Dialing wss://web.whatsapp.com/ws
mautrix-whatsapp        | 2021-05-26T15:49:40.873885643Z [May 26, 2021 15:49:40] [User/@redacted:redacted/DEBUG] Disconnecting due to failed session restore...
mautrix-whatsapp        | 2021-05-26T15:49:40.873923619Z [May 26, 2021 15:49:40] [User/@redacted:redacted/Conn/DEBUG] Disconnecting websocket
mautrix-whatsapp        | 2021-05-26T15:49:40.878012583Z panic: runtime error: invalid memory address or nil pointer dereference
mautrix-whatsapp        | 2021-05-26T15:49:40.878067024Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x85141f]
mautrix-whatsapp        | 2021-05-26T15:49:40.878085654Z 
mautrix-whatsapp        | 2021-05-26T15:49:40.878100053Z goroutine 69 [running]:
mautrix-whatsapp        | 2021-05-26T15:49:40.880137047Z github.com/Rhymen/go-whatsapp.(*Conn).Disconnect(0xc0001fe900, 0xc000311f80, 0x1)
mautrix-whatsapp        | 2021-05-26T15:49:40.880183166Z 	/builds/tulir/mautrix-whatsapp/.cache/pkg/mod/github.com/tulir/go-whatsapp@v0.5.3/conn.go:226 +0x7f
mautrix-whatsapp        | 2021-05-26T15:49:40.880200830Z main.(*User).RestoreSession(0xc000264750, 0xc0001fe900)
mautrix-whatsapp        | 2021-05-26T15:49:40.880212576Z 	/builds/tulir/mautrix-whatsapp/user.go:320 +0x36c
mautrix-whatsapp        | 2021-05-26T15:49:40.880223654Z main.(*User).Connect(0xc000264750, 0x0, 0x0)
mautrix-whatsapp        | 2021-05-26T15:49:40.880235966Z 	/builds/tulir/mautrix-whatsapp/user.go:276 +0x325
mautrix-whatsapp        | 2021-05-26T15:49:40.880259326Z created by main.(*Bridge).StartUsers
mautrix-whatsapp        | 2021-05-26T15:49:40.880277727Z 	/builds/tulir/mautrix-whatsapp/main.go:373 +0xca
```
any idea where I could start looking for the cause of this error?

**Comment by jahlives** [comment]
okay too big value on `sync_max_chat_age` was the reason. Played with that as I have troubles syncing all chats with all messages
