### ISSUE TITLE
Bridge crash after "list" - "pm"

### ISSUE THREAD

**Issue by jacotec** [tulir/mautrix-whatsapp#52]
Just doing a "list" command followed by a "pm xxxxxx" crashed the bridge with a panic. After the restart of the bridge the command worked. See the log part attached:

```
Mar 21 15:19:45 fblchat mautrix-whatsapp[14915]: [Mar 21, 2019 15:19:45] [Command handler/DEBUG] Importing xxxxxxxxxxxx@s.whatsapp.net for &{0xc000226460 0xc0002d40e0 0xc00009b9a0 0xc0002277c0 false true}
Mar 21 15:19:45 fblchat mautrix-whatsapp[14915]: panic: runtime error: invalid memory address or nil pointer dereference
Mar 21 15:19:45 fblchat mautrix-whatsapp[14915]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x788fee]
Mar 21 15:19:45 fblchat mautrix-whatsapp[14915]: goroutine 2691 [running]:
Mar 21 15:19:45 fblchat mautrix-whatsapp[14915]: github.com/Rhymen/go-whatsapp.(*Conn).write(0xc0001be0a0, 0x1, 0xc003ef6710, 0x10, 0xc00044e140, 0x4a, 0x50, 0xc0001f2380, 0x7f4f366eed98, 0x0)
Mar 21 15:19:45 fblchat mautrix-whatsapp[14915]: #011/opt/golang/pkg/mod/github.com/!rhymen/go-whatsapp@v0.0.2-0.20190313095452-eb9a9e486cd2/write.go:91 +0x3e
Mar 21 15:19:45 fblchat mautrix-whatsapp[14915]: github.com/Rhymen/go-whatsapp.(*Conn).writeJson(0xc0001be0a0, 0xc002ab0540, 0x3, 0x3, 0x100000000000099, 0x0, 0xa)
Mar 21 15:19:45 fblchat mautrix-whatsapp[14915]: #011/opt/golang/pkg/mod/github.com/!rhymen/go-whatsapp@v0.0.2-0.20190313095452-eb9a9e486cd2/write.go:27 +0x2c7
Mar 21 15:19:45 fblchat mautrix-whatsapp[14915]: github.com/Rhymen/go-whatsapp.(*Conn).GetProfilePicThumb(...)
Mar 21 15:19:45 fblchat mautrix-whatsapp[14915]: #011/opt/golang/pkg/mod/github.com/!rhymen/go-whatsapp@v0.0.2-0.20190313095452-eb9a9e486cd2/contact.go:25
Mar 21 15:19:45 fblchat mautrix-whatsapp[14915]: maunium.net/go/mautrix-whatsapp/whatsapp-ext.(*ExtendedConn).GetProfilePicThumb(0xc0002d40e0, 0xc002966580, 0x1b, 0x0, 0xc00010a8c0, 0xa)
Mar 21 15:19:45 fblchat mautrix-whatsapp[14915]: #011/opt/golang/mautrix-whatsapp/whatsapp-ext/whatsapp.go:121 +0x101
Mar 21 15:19:45 fblchat mautrix-whatsapp[14915]: main.(*Puppet).UpdateAvatar(0xc0035fe320, 0xc000228a80, 0x0, 0x1)
Mar 21 15:19:45 fblchat mautrix-whatsapp[14915]: #011/opt/golang/mautrix-whatsapp/puppet.go:132 +0x71d
Mar 21 15:19:45 fblchat mautrix-whatsapp[14915]: main.(*Puppet).Sync(0xc0035fe320, 0xc000228a80, 0xc00050b4a0, 0x1b, 0xc0001a237a, 0x5, 0x0, 0x0, 0x0, 0x0)
Mar 21 15:19:45 fblchat mautrix-whatsapp[14915]: #011/opt/golang/mautrix-whatsapp/puppet.go:194 +0x290
Mar 21 15:19:45 fblchat mautrix-whatsapp[14915]: main.(*CommandHandler).CommandPM(0xc0001a5ea0, 0xc003451ef8)
Mar 21 15:19:45 fblchat mautrix-whatsapp[14915]: #011/opt/golang/mautrix-whatsapp/commands.go:277 +0x41d
Mar 21 15:19:45 fblchat mautrix-whatsapp[14915]: main.(*CommandHandler).Handle(0xc0001a5ea0, 0xc002954880, 0x1e, 0xc000228a80, 0xc003d723e0, 0xf)
Mar 21 15:19:45 fblchat mautrix-whatsapp[14915]: #011/opt/golang/mautrix-whatsapp/commands.go:101 +0x20b
Mar 21 15:19:45 fblchat mautrix-whatsapp[14915]: main.(*MatrixHandler).HandleMessage(0xc0001accc0, 0xc000590240)
Mar 21 15:19:45 fblchat mautrix-whatsapp[14915]: #011/opt/golang/mautrix-whatsapp/matrix.go:161 +0x203
Mar 21 15:19:45 fblchat mautrix-whatsapp[14915]: created by maunium.net/go/mautrix-appservice.(*EventProcessor).Start
Mar 21 15:19:45 fblchat mautrix-whatsapp[14915]: #011/opt/golang/pkg/mod/maunium.net/go/mautrix-appservice@v0.1.0-alpha.3/eventprocessor.go:62 +0x55
Mar 21 15:19:45 fblchat systemd[1]: whatsapp-bridge.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 21 15:19:45 fblchat systemd[1]: whatsapp-bridge.service: Unit entered failed state.
Mar 21 15:19:45 fblchat systemd[1]: whatsapp-bridge.service: Failed with result 'exit-code'.
```

**Comment by rreuvekamp** [comment]
How old is the version of the bridge you're running? Were you logged into WhatsApp from the bridge when this panic occured?

There was a bug which made the bridge panic using these commands when you're not logged in, but that has since been fixed https://github.com/tulir/mautrix-whatsapp/pull/50

**Comment by jacotec** [comment]
Made a git clone today ... so it's pretty up to date

**Comment by tulir** [comment]
This is probably fixed by now, make a new issue with a new stack trace if not
